/* File: reconstructmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Sep 15 14:16:07 2015
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *reconstruct_error;
static PyObject *reconstruct_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(reconstruct_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = reconstruct_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = reconstruct_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(reconstruct,RECONSTRUCT)(double*,double*,int*,int*,double*,double*,double*,double*);
extern void F_FUNC(southwellbin,SOUTHWELLBIN)(double*,double*,double*,double*,int*,double*,double*,double*,double*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************** reconstruct ********************************/
static char doc_f2py_rout_reconstruct_reconstruct[] = "\
phasec = reconstruct(xang,yang,criteria,h,phase,[xdim,ydim])\n\nWrapper for ``reconstruct``.\
\n\nParameters\n----------\n"
"xang : in/output rank-2 array('d') with bounds (xdim,ydim)\n"
"yang : in/output rank-2 array('d') with bounds (xdim,ydim)\n"
"criteria : input float\n"
"h : input float\n"
"phase : in/output rank-2 array('d') with bounds (xdim,ydim)\n"
"\nOther Parameters\n----------------\n"
"xdim : input int, optional\n    Default: shape(xang,0)\n"
"ydim : input int, optional\n    Default: shape(xang,1)\n"
"\nReturns\n-------\n"
"phasec : rank-2 array('d') with bounds (xdim,ydim)";
/* extern void F_FUNC(reconstruct,RECONSTRUCT)(double*,double*,int*,int*,double*,double*,double*,double*); */
static PyObject *f2py_rout_reconstruct_reconstruct(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,int*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *xang = NULL;
  npy_intp xang_Dims[2] = {-1, -1};
  const int xang_Rank = 2;
  PyArrayObject *capi_xang_tmp = NULL;
  int capi_xang_intent = 0;
  PyObject *xang_capi = Py_None;
  double *yang = NULL;
  npy_intp yang_Dims[2] = {-1, -1};
  const int yang_Rank = 2;
  PyArrayObject *capi_yang_tmp = NULL;
  int capi_yang_intent = 0;
  PyObject *yang_capi = Py_None;
  int xdim = 0;
  PyObject *xdim_capi = Py_None;
  int ydim = 0;
  PyObject *ydim_capi = Py_None;
  double criteria = 0;
  PyObject *criteria_capi = Py_None;
  double h = 0;
  PyObject *h_capi = Py_None;
  double *phase = NULL;
  npy_intp phase_Dims[2] = {-1, -1};
  const int phase_Rank = 2;
  PyArrayObject *capi_phase_tmp = NULL;
  int capi_phase_intent = 0;
  PyObject *phase_capi = Py_None;
  double *phasec = NULL;
  npy_intp phasec_Dims[2] = {-1, -1};
  const int phasec_Rank = 2;
  PyArrayObject *capi_phasec_tmp = NULL;
  int capi_phasec_intent = 0;
  static char *capi_kwlist[] = {"xang","yang","criteria","h","phase","xdim","ydim",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OO:reconstruct.reconstruct",\
    capi_kwlist,&xang_capi,&yang_capi,&criteria_capi,&h_capi,&phase_capi,&xdim_capi,&ydim_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable h */
    f2py_success = double_from_pyobj(&h,h_capi,"reconstruct.reconstruct() 4th argument (h) can't be converted to double");
  if (f2py_success) {
  /* Processing variable criteria */
    f2py_success = double_from_pyobj(&criteria,criteria_capi,"reconstruct.reconstruct() 3rd argument (criteria) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xang */
  ;
  capi_xang_intent |= F2PY_INTENT_INOUT;
  capi_xang_tmp = array_from_pyobj(NPY_DOUBLE,xang_Dims,xang_Rank,capi_xang_intent,xang_capi);
  if (capi_xang_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(reconstruct_error,"failed in converting 1st argument `xang' of reconstruct.reconstruct to C/Fortran array" );
  } else {
    xang = (double *)(capi_xang_tmp->data);

  /* Processing variable xdim */
  if (xdim_capi == Py_None) xdim = shape(xang,0); else
    f2py_success = int_from_pyobj(&xdim,xdim_capi,"reconstruct.reconstruct() 1st keyword (xdim) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(xang,0)==xdim,"shape(xang,0)==xdim","1st keyword xdim","reconstruct:xdim=%d",xdim) {
  /* Processing variable ydim */
  if (ydim_capi == Py_None) ydim = shape(xang,1); else
    f2py_success = int_from_pyobj(&ydim,ydim_capi,"reconstruct.reconstruct() 2nd keyword (ydim) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(xang,1)==ydim,"shape(xang,1)==ydim","2nd keyword ydim","reconstruct:ydim=%d",ydim) {
  /* Processing variable phasec */
  phasec_Dims[0]=xdim,phasec_Dims[1]=ydim;
  capi_phasec_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_phasec_tmp = array_from_pyobj(NPY_DOUBLE,phasec_Dims,phasec_Rank,capi_phasec_intent,Py_None);
  if (capi_phasec_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(reconstruct_error,"failed in converting hidden `phasec' of reconstruct.reconstruct to C/Fortran array" );
  } else {
    phasec = (double *)(capi_phasec_tmp->data);

  /* Processing variable yang */
  yang_Dims[0]=xdim,yang_Dims[1]=ydim;
  capi_yang_intent |= F2PY_INTENT_INOUT;
  capi_yang_tmp = array_from_pyobj(NPY_DOUBLE,yang_Dims,yang_Rank,capi_yang_intent,yang_capi);
  if (capi_yang_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(reconstruct_error,"failed in converting 2nd argument `yang' of reconstruct.reconstruct to C/Fortran array" );
  } else {
    yang = (double *)(capi_yang_tmp->data);

  /* Processing variable phase */
  phase_Dims[0]=xdim,phase_Dims[1]=ydim;
  capi_phase_intent |= F2PY_INTENT_INOUT;
  capi_phase_tmp = array_from_pyobj(NPY_DOUBLE,phase_Dims,phase_Rank,capi_phase_intent,phase_capi);
  if (capi_phase_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(reconstruct_error,"failed in converting 5th argument `phase' of reconstruct.reconstruct to C/Fortran array" );
  } else {
    phase = (double *)(capi_phase_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(xang,yang,&xdim,&ydim,&criteria,&h,phase,phasec);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_phasec_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_phase_tmp!=phase_capi) {
    Py_XDECREF(capi_phase_tmp); }
  }  /*if (capi_phase_tmp == NULL) ... else of phase*/
  /* End of cleaning variable phase */
  if((PyObject *)capi_yang_tmp!=yang_capi) {
    Py_XDECREF(capi_yang_tmp); }
  }  /*if (capi_yang_tmp == NULL) ... else of yang*/
  /* End of cleaning variable yang */
  }  /*if (capi_phasec_tmp == NULL) ... else of phasec*/
  /* End of cleaning variable phasec */
  } /*CHECKSCALAR(shape(xang,1)==ydim)*/
  } /*if (f2py_success) of ydim*/
  /* End of cleaning variable ydim */
  } /*CHECKSCALAR(shape(xang,0)==xdim)*/
  } /*if (f2py_success) of xdim*/
  /* End of cleaning variable xdim */
  if((PyObject *)capi_xang_tmp!=xang_capi) {
    Py_XDECREF(capi_xang_tmp); }
  }  /*if (capi_xang_tmp == NULL) ... else of xang*/
  /* End of cleaning variable xang */
  } /*if (f2py_success) of criteria*/
  /* End of cleaning variable criteria */
  } /*if (f2py_success) of h*/
  /* End of cleaning variable h */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of reconstruct *****************************/

/******************************** southwellbin ********************************/
static char doc_f2py_rout_reconstruct_southwellbin[] = "\
xang,yang,phase = southwellbin(x,y,l,m,binsize,xdim,ydim,[num])\n\nWrapper for ``southwellbin``.\
\n\nParameters\n----------\n"
"x : input rank-1 array('d') with bounds (num)\n"
"y : input rank-1 array('d') with bounds (num)\n"
"l : input rank-1 array('d') with bounds (num)\n"
"m : input rank-1 array('d') with bounds (num)\n"
"binsize : input float\n"
"xdim : input int\n"
"ydim : input int\n"
"\nOther Parameters\n----------------\n"
"num : input int, optional\n    Default: len(x)\n"
"\nReturns\n-------\n"
"xang : rank-2 array('d') with bounds (xdim,ydim)\n"
"yang : rank-2 array('d') with bounds (xdim,ydim)\n"
"phase : rank-2 array('d') with bounds (xdim,ydim)";
/* extern void F_FUNC(southwellbin,SOUTHWELLBIN)(double*,double*,double*,double*,int*,double*,double*,double*,double*,int*,int*); */
static PyObject *f2py_rout_reconstruct_southwellbin(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,int*,double*,double*,double*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  double *l = NULL;
  npy_intp l_Dims[1] = {-1};
  const int l_Rank = 1;
  PyArrayObject *capi_l_tmp = NULL;
  int capi_l_intent = 0;
  PyObject *l_capi = Py_None;
  double *m = NULL;
  npy_intp m_Dims[1] = {-1};
  const int m_Rank = 1;
  PyArrayObject *capi_m_tmp = NULL;
  int capi_m_intent = 0;
  PyObject *m_capi = Py_None;
  int num = 0;
  PyObject *num_capi = Py_None;
  double binsize = 0;
  PyObject *binsize_capi = Py_None;
  double *xang = NULL;
  npy_intp xang_Dims[2] = {-1, -1};
  const int xang_Rank = 2;
  PyArrayObject *capi_xang_tmp = NULL;
  int capi_xang_intent = 0;
  double *yang = NULL;
  npy_intp yang_Dims[2] = {-1, -1};
  const int yang_Rank = 2;
  PyArrayObject *capi_yang_tmp = NULL;
  int capi_yang_intent = 0;
  double *phase = NULL;
  npy_intp phase_Dims[2] = {-1, -1};
  const int phase_Rank = 2;
  PyArrayObject *capi_phase_tmp = NULL;
  int capi_phase_intent = 0;
  int xdim = 0;
  PyObject *xdim_capi = Py_None;
  int ydim = 0;
  PyObject *ydim_capi = Py_None;
  static char *capi_kwlist[] = {"x","y","l","m","binsize","xdim","ydim","num",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|O:reconstruct.southwellbin",\
    capi_kwlist,&x_capi,&y_capi,&l_capi,&m_capi,&binsize_capi,&xdim_capi,&ydim_capi,&num_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xdim */
    f2py_success = int_from_pyobj(&xdim,xdim_capi,"reconstruct.southwellbin() 6th argument (xdim) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ydim */
    f2py_success = int_from_pyobj(&ydim,ydim_capi,"reconstruct.southwellbin() 7th argument (ydim) can't be converted to int");
  if (f2py_success) {
  /* Processing variable binsize */
    f2py_success = double_from_pyobj(&binsize,binsize_capi,"reconstruct.southwellbin() 5th argument (binsize) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(reconstruct_error,"failed in converting 1st argument `x' of reconstruct.southwellbin to C/Fortran array" );
  } else {
    x = (double *)(capi_x_tmp->data);

  /* Processing variable num */
  if (num_capi == Py_None) num = len(x); else
    f2py_success = int_from_pyobj(&num,num_capi,"reconstruct.southwellbin() 1st keyword (num) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(x)>=num,"len(x)>=num","1st keyword num","southwellbin:num=%d",num) {
  /* Processing variable phase */
  phase_Dims[0]=xdim,phase_Dims[1]=ydim;
  capi_phase_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_phase_tmp = array_from_pyobj(NPY_DOUBLE,phase_Dims,phase_Rank,capi_phase_intent,Py_None);
  if (capi_phase_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(reconstruct_error,"failed in converting hidden `phase' of reconstruct.southwellbin to C/Fortran array" );
  } else {
    phase = (double *)(capi_phase_tmp->data);

  /* Processing variable xang */
  xang_Dims[0]=xdim,xang_Dims[1]=ydim;
  capi_xang_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_xang_tmp = array_from_pyobj(NPY_DOUBLE,xang_Dims,xang_Rank,capi_xang_intent,Py_None);
  if (capi_xang_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(reconstruct_error,"failed in converting hidden `xang' of reconstruct.southwellbin to C/Fortran array" );
  } else {
    xang = (double *)(capi_xang_tmp->data);

  /* Processing variable m */
  m_Dims[0]=num;
  capi_m_intent |= F2PY_INTENT_IN;
  capi_m_tmp = array_from_pyobj(NPY_DOUBLE,m_Dims,m_Rank,capi_m_intent,m_capi);
  if (capi_m_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(reconstruct_error,"failed in converting 4th argument `m' of reconstruct.southwellbin to C/Fortran array" );
  } else {
    m = (double *)(capi_m_tmp->data);

  /* Processing variable l */
  l_Dims[0]=num;
  capi_l_intent |= F2PY_INTENT_IN;
  capi_l_tmp = array_from_pyobj(NPY_DOUBLE,l_Dims,l_Rank,capi_l_intent,l_capi);
  if (capi_l_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(reconstruct_error,"failed in converting 3rd argument `l' of reconstruct.southwellbin to C/Fortran array" );
  } else {
    l = (double *)(capi_l_tmp->data);

  /* Processing variable yang */
  yang_Dims[0]=xdim,yang_Dims[1]=ydim;
  capi_yang_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_yang_tmp = array_from_pyobj(NPY_DOUBLE,yang_Dims,yang_Rank,capi_yang_intent,Py_None);
  if (capi_yang_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(reconstruct_error,"failed in converting hidden `yang' of reconstruct.southwellbin to C/Fortran array" );
  } else {
    yang = (double *)(capi_yang_tmp->data);

  /* Processing variable y */
  y_Dims[0]=num;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(reconstruct_error,"failed in converting 2nd argument `y' of reconstruct.southwellbin to C/Fortran array" );
  } else {
    y = (double *)(capi_y_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(x,y,l,m,&num,&binsize,xang,yang,phase,&xdim,&ydim);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNN",capi_xang_tmp,capi_yang_tmp,capi_phase_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
  }  /*if (capi_yang_tmp == NULL) ... else of yang*/
  /* End of cleaning variable yang */
  if((PyObject *)capi_l_tmp!=l_capi) {
    Py_XDECREF(capi_l_tmp); }
  }  /*if (capi_l_tmp == NULL) ... else of l*/
  /* End of cleaning variable l */
  if((PyObject *)capi_m_tmp!=m_capi) {
    Py_XDECREF(capi_m_tmp); }
  }  /*if (capi_m_tmp == NULL) ... else of m*/
  /* End of cleaning variable m */
  }  /*if (capi_xang_tmp == NULL) ... else of xang*/
  /* End of cleaning variable xang */
  }  /*if (capi_phase_tmp == NULL) ... else of phase*/
  /* End of cleaning variable phase */
  } /*CHECKSCALAR(len(x)>=num)*/
  } /*if (f2py_success) of num*/
  /* End of cleaning variable num */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of binsize*/
  /* End of cleaning variable binsize */
  } /*if (f2py_success) of ydim*/
  /* End of cleaning variable ydim */
  } /*if (f2py_success) of xdim*/
  /* End of cleaning variable xdim */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of southwellbin ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"reconstruct",-1,{{-1}},0,(char *)F_FUNC(reconstruct,RECONSTRUCT),(f2py_init_func)f2py_rout_reconstruct_reconstruct,doc_f2py_rout_reconstruct_reconstruct},
  {"southwellbin",-1,{{-1}},0,(char *)F_FUNC(southwellbin,SOUTHWELLBIN),(f2py_init_func)f2py_rout_reconstruct_southwellbin,doc_f2py_rout_reconstruct_southwellbin},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "reconstruct",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_reconstruct(void) {
#else
#define RETVAL
PyMODINIT_FUNC initreconstruct(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = reconstruct_module = PyModule_Create(&moduledef);
#else
  m = reconstruct_module = Py_InitModule("reconstruct", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module reconstruct (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'reconstruct' is auto-generated with f2py (version:2).\nFunctions:\n"
"  phasec = reconstruct(xang,yang,criteria,h,phase,xdim=shape(xang,0),ydim=shape(xang,1))\n"
"  xang,yang,phase = southwellbin(x,y,l,m,binsize,xdim,ydim,num=len(x))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  reconstruct_error = PyErr_NewException ("reconstruct.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));


/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"reconstruct");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
